/**
 * Screen 10 — Recommendation Details.
 *
 * The audit trail for one recommendation: every step of the arithmetic, in order,
 * with the source of each number.
 *
 * This screen is why the engine is deterministic. A user can follow the
 * calculation from purchase amount to final dollar value and reproduce it on
 * paper. The explanation layer phrases those steps; it does not compute them.
 */
import { useLocalSearchParams } from 'expo-router';

import { DisclaimerNotice } from '@/components/Disclaimers';
import { PlaceholderSection } from '@/components/PlaceholderSection';
import { Card } from '@/components/ui/Card';
import { Screen } from '@/components/ui/Screen';
import { VStack } from '@/components/ui/Stack';
import { Text } from '@/components/ui/Text';

/** The order the engine applies its steps in. Documented in REWARDS_ENGINE.md. */
const CALCULATION_STEPS: readonly string[] = [
  'Collect every active reward rule for the card',
  'Check whether this purchase satisfies each rule',
  'Apply merchant and category exclusions',
  'Check activation, where the rule needs it',
  'Work out how much of the cap is left',
  'Apply the base and bonus rates',
  'Apply any active merchant offer',
  'Subtract the foreign transaction fee, if one applies',
  'Convert points or miles using your own valuation',
  'Assign a confidence level',
];

export default function RecommendationDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();

  return (
    <Screen scroll accessibilityLabel="Recommendation details" testID="recommendation-details">
      <VStack gap="xl">
        <VStack gap="sm">
          <Text variant="title1" accessibilityRole="header">
            How we worked this out
          </Text>
          <Text variant="footnote" tone="tertiary">
            Recommendation {id ?? 'unknown'}
          </Text>
        </VStack>

        <Card>
          <VStack gap="md">
            <Text variant="title3" accessibilityRole="header">
              The steps, in order
            </Text>
            <VStack gap="sm">
              {CALCULATION_STEPS.map((step, index) => (
                <Text
                  key={step}
                  variant="callout"
                  tone="secondary"
                  accessibilityLabel={`Step ${index + 1}. ${step}`}
                >
                  {index + 1}. {step}
                </Text>
              ))}
            </VStack>
            <Text variant="footnote" tone="tertiary">
              Every one of these steps is a plain TypeScript function reading validated database
              records. Nothing on this screen is generated by a model.
            </Text>
          </VStack>
        </Card>

        <PlaceholderSection
          phase="Phase 4"
          title="Calculation breakdown"
          description="The actual numbers for this recommendation: qualifying spend within and beyond the cap, the rate applied to each portion, gross reward units, the valuation used, offer value, statement credits, fees subtracted, and the net dollar value."
          testID="details-breakdown"
        />

        <PlaceholderSection
          phase="Phase 4"
          title="Why this rule applied"
          description="The rule that won, which conditions it satisfied, and why the runner-up rules on the same card lost."
          testID="details-rule"
        />

        <PlaceholderSection
          phase="Phase 6"
          title="Source and verification"
          description="The source document behind the rate, when it was last verified, its verification status, and the full history of changes."
          testID="details-source"
        />

        <DisclaimerNotice kind="financial" />
        <DisclaimerNotice kind="merchant_category" />
      </VStack>
    </Screen>
  );
}
